### ISSUE TITLE
Question,Help me!!

### ISSUE THREAD

**Issue by Caibiy** [encody/SimpleStarRating#2]
hi, guys.

My english is poor,but i want you help me !

i want set marin-right for star,like this!
![star](https://cloud.githubusercontent.com/assets/16449809/19303320/c28dd1de-909a-11e6-8fd7-e42d5a8008c4.png)

**Comment by encody** [comment]
Add the `margin-right` style to the `.rating .star::before` selector:

```
.rating .star::before {
    display: inline-block;
    color: $unfilled-star-color;
    content: '☆';
    width: 1em;
    height: 1em;
    margin-right: 0.5em;
}
```
