### ISSUE TITLE
Clear stars

### ISSUE THREAD

**Issue by GeometricProgress** [encody/SimpleStarRating#3]
Hi 
Great project and easy to implement.  Stupid question, how could I invoke a method to clear the stars when I click a button / link etc.  

Thanks Mark

**Comment by encody** [comment]
Call `simpleStarRating.setCurrentRating(0)`.

**Comment by GeometricProgress** [comment]
Thank you.  You are a star. No Pun intended :)

**Comment by PaulYBChiang** [comment]
> Thank you. You are a star. No Pun intended :)



> Call `simpleStarRating.setCurrentRating(0)`.

Leaving an invisible 'star' in the left side could be a better design and zero rating should be the choice of users.

**Comment by PaulYBChiang** [comment]
if(starRating==currentRating & currentRating==1)
	        starRating=-1;
                    var starRating = starClicked + 1;
